imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CommerceBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@CompteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host: mail.cypriengilbert.com
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    port: 25

fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:   UserBundle\Entity\User  # La classe de l'entité User que nous utilisons
    registration:
        form:
            type: UserBundle\Form\RegistrationType
        confirmation:
            enabled: false

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []


vich_uploader:
    db_driver: orm
    mappings:
        colorFile:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/color/thumbnail
            upload_destination: %kernel.root_dir%/../web//upload/color/thumbnail
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        photoFile:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/mediatheque
            upload_destination: %kernel.root_dir%/../web//upload/mediatheque
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        colorNoeud1File:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/color/noeud1
            upload_destination: %kernel.root_dir%/../web//upload/color/noeud1
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        colorNoeud2File:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/color/noeud2
            upload_destination: %kernel.root_dir%/../web//upload/color/noeud2
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        colorNoeud3File:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/color/noeud3
            upload_destination: %kernel.root_dir%/../web//upload/color/noeud3
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/image_produit_predefini/
            upload_destination: %kernel.root_dir%/../web//upload/image_produit_predefini/
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        imageCollection:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/image_collection/
            upload_destination: %kernel.root_dir%/../web//upload/image_collection/
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        imageCollectionCarre:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/image_collection/
            upload_destination: %kernel.root_dir%/../web//upload/image_collection/
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        imageCollectionIcone:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /upload/image_collection/
            upload_destination: %kernel.root_dir%/../web//upload/image_collection/
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
