<?php

namespace CommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddedProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddedProductRepository extends EntityRepository
{
}
