<?php

namespace CommerceBundle\Repository;

/**
 * AutomaticDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutomaticDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
