<?php

namespace CommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * collectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class collectionRepository extends EntityRepository
{
}
