<?php

namespace CommerceBundle\Repository;

/**
 * defined_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class defined_productRepository extends \Doctrine\ORM\EntityRepository
{
}
