<?php

namespace CommerceBundle\Repository;

/**
 * ProDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
