<?php

namespace CommerceBundle\Repository;

/**
 * StockListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockListRepository extends \Doctrine\ORM\EntityRepository
{
}
