<?php

namespace CommerceBundle\Repository;

/**
 * SurveyResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
