<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ZendPdf\\' => array($vendorDir . '/zendframework/zendpdf/library'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Spraed\\PDFGeneratorBundle' => array($vendorDir . '/spraed/pdf-generator-bundle'),
    'SensioLabs\\Security' => array($vendorDir . '/sensiolabs/security-checker'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Ps\\PdfBundle' => array($vendorDir . '/psliwa/pdf-bundle'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'PHPPdf' => array($vendorDir . '/psliwa/php-pdf/lib'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'Knp\\Snappy' => array($vendorDir . '/knplabs/knp-snappy/src'),
    'Imagine' => array($vendorDir . '/psliwa/php-pdf/lib'),
    'Doctrine\\ORM\\' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
