<?php

namespace CompteBundle\Repository;

/**
 * invoiceEditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invoiceEditRepository extends \Doctrine\ORM\EntityRepository
{
}
