<?php

namespace CompteBundle\Repository;

/**
 * MonthlyInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
